### PR TITLE
Fix #351

### LINKED ISSUE #351: Unpin tiles from stat menu does not work
Downloaded installer using iex ((New-Object System.Net.WebClient).DownloadString('https://git.io/debloat'))
C:\Temp\Windows10Debloater exists. Skipping.
Transcript started, output file is C:\Temp\Windows10Debloater\PowerShell_transcript.DESKTOP-AG2KNCL.1esoVeSs.20210125142851.txt
Unpinning all tiles from the start menu
Unpinning all tiles from the start menu

While all the other feature work , the unpinning tiles feature hangs as above. On one instance explorer.exe was killed and had to be restarted.

Windows 10 OS Build 18363.1316

Start time: 20210125142851
Username: DESKTOP-A\work
RunAs User: DESKTOP-A\work
Configuration Name: 
Machine: DESKTOP-A(Microsoft Windows NT 10.0.18363.0)
Host Application: C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe
Process ID: 22336
PSVersion: 5.1.18362.1171
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.18362.1171
BuildVersion: 10.0.18362.1171
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

### PR DESCRIPTION
**Pull request by captainsalt**
A fix for #351.  This is a different script from the same thread the original script is from that removes everything from the start menu.
 I used it on my own machine and it worked.

### CODE REVIEW

**Comment by felipecrs** [comment]
Which thread is that?

**Comment by felipecrs** [comment]
Just found: https://superuser.com/questions/1068382/how-to-remove-all-the-tiles-in-the-windows-10-start-menu

**Comment by captainsalt** [comment]
[This Thread](https://superuser.com/a/1442733)
The link to this answer is also in my commit on the first line

**Comment by felipecrs** [comment]
Thanks so much.

**Comment by felipecrs** [comment]
I just tested here and it works well. However, I think it should also be updated in the GUI version, or maybe the others scripts as well.

**Comment by captainsalt** [comment]
I assumed that the GUI called the scripts. Thank you for pointing it out and I'll look into it more

**Comment by captainsalt** [comment]
Tested on a windows VM. Both the CLI and the GUI scripts worked

**Comment by Sycnex** [comment]
Will check this later today. Thank you.

**Pull request merged**
