### PR TITLE
Added buttons to remove/restore '3D Objects' from Quick Access

### PR DESCRIPTION
**Pull request by christianberkman**
Functions to remove/restore '3D Objects' from Quick Access was present in the script but not was never called. Added buttons so the user may choose to remove or restore.

### CODE REVIEW

**Comment by Sycnex** [comment]
Will check later today. Thank you.

**Comment by christianberkman** [comment]
Great. Sorry for the whitespace noise.

**Comment by Sycnex** [comment]
I'm taking a look at this. Will check it out further tonight/tomorrow morning. Might need to make adjustments after the most recent pull request that was merged.

**Comment by Sycnex** [comment]
I still need to think about this. I'm trying to work on a new GUI in my spare time (however little I have) and I would like to implement this in the new gui.

**Pull request closed without merging**
