### PR TITLE
Added Dark Mode, Removed 3D Objects, Fixed OneDrive not closing explorer, Optimized Debloat all to be error free

### PR DESCRIPTION
**Pull request by Gray-0men**
If you have any questions about this pull request feel free to ask. I keep making them and then adding more to the project since I remote into new windows 10 install computers on a daily basis so I'm running this thing often and fine tuning the hell out of it. 

I'll explain whatever is needed to get this merged

### CODE REVIEW

**Comment by Sycnex** [comment]
Can you keep all of the write-host to write-output please? Write-host is not recommended for use by microsoft, especially with anything to do with loops.

**Comment by Gray-0men** [comment]
Should I remove the "quoted text" that was after each Write-Host as well? 

Write-Output does nothing to the text afterwards and it's not displayed in the LOG or the Power-Shell window, mostly I was using it as a progress indicator or a visual readout to see what the Power-Shell window was doing at that exact moment since most of the time it looks frozen with nothing
*edit*
I might as well just remove all the write-host lines then since write-output just pipes data into something and doesn't display it. The quoted text after it does nothing if i'm not mistaken

I can also just add Verbose at the end of every command but write-host just looks neater and is customized rather than that random data and text that verbose spits out in bright blue text

**Comment by Gray-0men** [comment]
also looks like the conflict on my pull request here is just a tab indent on each of the lines in the one drive line of code. Or there are 4 less spaces than yours

**Comment by Sycnex** [comment]
As long as it doesn't break the loops then we can keep it.

**Pull request merged**
