### PR TITLE
windows 10 disabler.ps1

### PR DESCRIPTION
**Pull request by Brandonbr1**
I added a Windows 10 services disabler  to disable useless windows 10 services to make your computer run faster and all these can be safely disabled

### CODE REVIEW

**Comment by Sycnex** [comment]
Looks good. I’ll merge it sometime hopefully this week.

**Comment by Brandonbr1** [comment]
script delted

I wanted to point out that i have a 

more updated script here: [my more updated script ](https://github.com/Sycnex/Windows10Debloater/pull/396)

ps: i actidently deleted the respority

**Comment by Brandonbr1** [comment]
Deer Richard Newton

HI, Richard Newton I would like to say that i have updated the script


here is the newest script:
https://github.com/Sycnex/Windows10Debloater/pull/397

**Comment by Brandonbr1** [comment]
Deer Richard Newton,

HI, Richard Newton I would like to say that i have updated the script


here is the latest version of my  script:
https://github.com/Sycnex/Windows10Debloater/pull/397

sincerely,Brandon

**Comment by Brandonbr1** [comment]
Dear, Richard Newton

HI, Richard Newton, I would like to say that I have updated the script

ps: i accidentally deleted the  repository


here is the latest version of my  script:https://github.com/Sycnex
/Windows10Debloater/pull/398

sincerely, Brandon Mohammed

**Comment by Brandonbr1** [comment]
Dear, Richard Newton

HI, Richard Newton, I would like to say that I have updated the script

ps: i accidentally deleted the  repository  and got nervous when creating a
pull request


here is the latest version of my  script:https://github.com/Sycnex
/Windows10Debloater/pull/398

sincerely, Brandon Mohammed

**Pull request closed without merging**
