### PR TITLE
Making the Debloating process easier for the novice user.

### PR DESCRIPTION
**Pull request by jake01756**
I made an installer for the debloating of Windows 10. It will install the files into the C:\Windows\System32\Windows 10 Debloater Directory, because that was the easiest place to put them given that an administrator powershell and command prompt always open to C:\Windows\System32.

### CODE REVIEW

**Comment by Sycnex** [comment]
Why not put this in the C:\Temp\Windows10Debloater folder?

**Comment by sheldonhull** [comment]
I wouldn't want any app installing into windows directory directly. I'd also add that something like this isn't really imo designed to be user friendly anyway, as it's script modifications of windows. I'd wager security software would have an issue with it as well. Just my 10 cents

**Comment by Sycnex** [comment]
I would agree with Sheldon. From a security point of view, this is certainly not best practice. I’d like to check out what you have made, but I think the best place to put this is in the C:\Temp\Windows10Debloater location (or just in C:\Temp).

**Comment by axieum** [comment]
Installing such program, in my opinion, is out of the scope of this script's purpose. How would you update it? How often will you run the script?

**Comment by jake01756** [comment]
Maybe I could change it to install in to the %DriveLetter%\Temp\Win10Debloat directory. It’s also just additional installation option. It adds itself to the start menu under accessories (I think, I’m not sure if I enabled it). It would have to be run after every feature update. So max 2 times a year, if that.

**Pull request closed without merging**
