### PR TITLE
Added easy launch batchs

### PR DESCRIPTION
**Pull request by Woomymy**
Added batch scripts for launch as administrator

### CODE REVIEW

**Comment by Woomymy** [comment]
Updated !

**Comment by x0rld** [comment]
you should accept it, It's easier

**Review by Norrodar — APPROVED** [review]

**Comment by Sycnex** [comment]
@Woomy4680-exe - My apologies. I took a long break from this project and since I came back I am working my way down the pull requests and issues. I am looking at this and will hopefully review it all tonight and/or tomorrow morning. Thank you!

**Comment by Woomymy** [comment]
Hey, No probem. Take care of you. Thanks for merging the PR!

**Pull request merged**
